### ISSUE TITLE
Latest progeny is not published correctly on npm

### ISSUE THREAD

**Issue by kaizau** [es128/progeny#14]
Seems like the npm version of progeny is outdated, even though the version number is correct. 

If you `npm install` and check `node_modules/progeny/{lib,src}`, you'll notice that it's missing glob handling. You can also verify that on https://www.npmjs.com/package/progeny, the listed depencies do not match what's here on Github.

**Comment by es128** [comment]
I just republished as 0.5.3. Seems to be ok now. Thanks for reporting.

**Comment by es128** [comment]
Oh well turns out I wasn't really paying attention. The glob features weren't in 0.5.2 and hadn't ever been published. Unpublishing 0.5.3. Will take a look at it to make sure everything seems ok, and if so will publish as 0.6.0.
